# Generated by Django 4.1.1 on 2022-09-28 02:06

import django.core.validators
from django.db import migrations, models
import servicios.validators


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_rename_cliente_persona_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='correo',
            field=models.EmailField(default='user@mail.com', max_length=254, validators=[django.core.validators.EmailValidator('No es un email válido')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='unidades',
            field=models.CharField(choices=[('u', 'Unidades'), ('kg', 'Kilogramos')], default='u', max_length=2),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='precio_correo',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[servicios.validators.validar_par]),
        ),
    ]
